EFpartialClassDemo/Controllers/CategoriesController.cs
#nullable disable
using EFpartialClassDemo.Entities;
using EFpartialClassDemo.Services;
using Microsoft.AspNetCore.Mvc;

namespace EFpartialClassDemo.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoriesController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        // GET: Categories
        public IActionResult Index()
        {
            List<Category> categoryList = _categoryService.Query().ToList();
            return View(categoryList);
        }

        // GET: Categories/Details/5
        public IActionResult Details(int id)
        {
            Category category = _categoryService.Query().SingleOrDefault(c => c.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                if (_categoryService.Add(category))
                    return RedirectToAction(nameof(Index));
                ModelState.AddModelError("", "Category with same name exists!");
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public IActionResult Edit(int id)
        {
            Category category = _categoryService.Query().SingleOrDefault(c => c.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                if (_categoryService.Update(category))
                    return RedirectToAction(nameof(Index));
                ModelState.AddModelError("", "Category with same name exists!");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public IActionResult Delete(int id)
        {
            Category category = _categoryService.Query().SingleOrDefault(c => c.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (!_categoryService.Delete(id))
                TempData["DeleteCategoryMessage"] = "Category cannot be deleted because it has products!";
            return RedirectToAction(nameof(Index));
        }
	}
}

EFpartialClassDemo/Controllers/DatabaseController.cs
using EFpartialClassDemo.Contexts;
using EFpartialClassDemo.Entities;
using Microsoft.AspNetCore.Mvc;

namespace EFpartialClassDemo.Controllers
{
    public class DatabaseController : Controller
    {
        private readonly ProductsContext _productsContext;

        public DatabaseController(ProductsContext productsContext)
        {
            _productsContext = productsContext;
        }

        public IActionResult Seed()
        {
            var products = _productsContext.Products.ToList();
            _productsContext.Products.RemoveRange(products);

            var categories = _productsContext.Categories.ToList();
            _productsContext.Categories.RemoveRange(categories);

            _productsContext.Categories.Add(new Category()
            {
                Name = "Computer",
                Products = new List<Product>()
                {
                    new Product()
                    {
                        Name = "Laptop",
                        UnitPrice = 3000.5,
                        ExpirationDate = new DateTime(2032, 1, 27)
                    },
                    new Product()
                    {
                        Name = "Mouse",
                        UnitPrice = 20.5,
                        ExpirationDate = new DateTime(2027, 5, 19)
                    },
                    new Product()
                    {
                        Name = "Keyboard",
                        UnitPrice = 40,
                    },
                    new Product()
                    {
                        Name = "Monitor",
                        UnitPrice = 2500,
                    }
                }
            });

            _productsContext.Categories.Add(new Category()
            {
                Name = "Home Theater System",
                Products = new List<Product>()
                {
                    new Product()
                    {
                        Name = "Speaker",
                        UnitPrice = 2500
                    },
                    new Product()
                    {
                        Name = "Receiver",
                        UnitPrice = 5000,
                    },
                    new Product()
                    {
                        Name = "Equalizer",
                        UnitPrice = 1000,
                    }
                }
            });

            _productsContext.SaveChanges();

            return Content("<label style=\"color:red;\"><b>Database seed successful.</b></label>", "text/html");
        }
    }
}

EFpartialClassDemo/Controllers/ProductsCategoriesJoinController.cs
#nullable disable
using EFpartialClassDemo.Models;
using EFpartialClassDemo.Services;
using Microsoft.AspNetCore.Mvc;

namespace EFpartialClassDemo.Controllers
{
    public class ProductsCategoriesJoinController : Controller
    {
        private readonly IProductService _productService;

        public ProductsCategoriesJoinController(IProductService productService)
        {
            _productService = productService;
        }

        // GET: ProductsCategoriesJoin
        public IActionResult Index()
        {
            List<ProductCategoryJoinModel> list = _productService.ProductCategoriesJoinList();
            return View(list);
        }
	}
}

EFpartialClassDemo/Controllers/ProductsController.cs
using EFpartialClassDemo.Entities;
using EFpartialClassDemo.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EFpartialClassDemo.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;

        public ProductsController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }

        // GET: ProductsController
        public ActionResult Index()
        {
            var products = _productService.Query().ToList();
            return View(products);
        }

        // GET: ProductsController/Details/5
        public ActionResult Details(int id)
        {
            var product = _productService.Query().SingleOrDefault(p => p.Id == id);
            if (product == null)
                return NotFound();
            return View(product);
        }

        // GET: ProductsController/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(_categoryService.Query().ToList(), "Id", "Name");
            return View();
        }

        // POST: ProductsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product)
        {
           if (ModelState.IsValid)
            {
                if (_productService.Add(product))
                    return RedirectToAction(nameof(Index));
                ModelState.AddModelError("", "Product with same name exists!");
            }
            ViewBag.CategoryId = new SelectList(_categoryService.Query().ToList(), "Id", "Name", product.CategoryId);
            return View(product);
        }

        // GET: ProductsController/Edit/5
        public ActionResult Edit(int id)
        {
            var product = _productService.Query().SingleOrDefault(p => p.Id == id);
            if (product == null)
                return NotFound();
            ViewBag.CategoryId = new SelectList(_categoryService.Query().ToList(), "Id", "Name", product.CategoryId);
            return View(product);
        }

        // POST: ProductsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                if (_productService.Update(product))
                    return RedirectToAction(nameof(Index));
                ModelState.AddModelError("", "Product with same name exists!");
            }
            ViewBag.CategoryId = new SelectList(_categoryService.Query().ToList(), "Id", "Name", product.CategoryId);
            return View(product);
        }

        // GET: ProductsController/Delete/5
        public ActionResult Delete(int id)
        {
            var product = _productService.Query().SingleOrDefault(p => p.Id == id);
            if (product == null)
                return NotFound();
            return View(product);
        }

        // POST: ProductsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            _productService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

EFpartialClassDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EF - Partial Class Demo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EFpartialClassDemo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EF - Partial Class Demo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Database" asp-action="Seed">Seed Database</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductsCategoriesJoin" asp-action="Index">Products Categories Join</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Today.Year
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>